### ISSUE TITLE
Warning page text and "continue" button are cut off in screen with large text and display size

### ISSUE THREAD

**Issue by lokety** [fatorius/DUCO-Android-Miner#1]
Google Pixel 7
I have large text and display size set as my eyes are old.
The bottom part of the warn page gets cut off as a result and I have to reduce these settings to get to the mining page.
Thanks.

**Comment by fatorius** [comment]
Hello! Thanks for your feedback!


I think [commit 46602200](https://github.com/fatorius/DUCO-Android-Miner/commit/46602209f7514c67ec10d7bf2ac3c30d2ebb4b7e) solves this issue by putting all the elements inside of a Scroll View container.
I made this changes on both the Warning and the Initial pages, but I had only tested on a emulated Google Pixel 6 Pro with the largest font size.
I'm [attaching a recording](https://github.com/fatorius/DUCO-Android-Miner/assets/47526637/15275341-8f09-43e8-98d6-859165327f6a) of the emulated layout for you to check it out.


Soon I'll be updating the version on Play Store with this fixings in case you had installed the app through it.
