### ISSUE TITLE
Duinocoin Web Wallet site detects "incorrect mining key" from this app

### ISSUE THREAD

**Issue by lokety** [fatorius/DUCO-Android-Miner#2]
Google Pixel 7
I have a mining key set in my account. As the app starts mining, I see this message on https://wallet.duinocoin.com/ under the Miners list:

> Invalid miner configuration detected
> One or more miner is trying to mine on your account but has an incorrect mining key entered. If it's yours, double check your config files.

The log looks fine though, reporting a reasonable hashrate and no connection errors.

**Comment by fatorius** [comment]
Hello! Thanks for your feedback!

I see why this is happening. It turns out that the mining key wasn't being stored in the app, but I'm already working on fixing it. I'll let you know when it's done!

**Comment by fatorius** [comment]
Commit [4dca12f](https://github.com/fatorius/DUCO-Android-Miner/commit/4dca12f4b64181b451f4f602bed406b5ff308bcd) solves this issue
